# URL de conexión: debe coincidir con el nombre de la DB que creaste en docker run (-e POSTGRES_DB=realworld)
# Nota: Si tu app corre en Docker, usa 'realworld-db' como host.
# Si corre fuera de Docker, usa 'localhost'.
spring.datasource.url=jdbc:postgresql://localhost:5432/realworld

spring.datasource.username=flutter_user
spring.datasource.password=1234abcd

# Esto es obligatorio para que Hibernate sepa qué dialecto usar
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Recomendado para desarrollo (crea/actualiza las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update